//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studInfo
    {
        public int AdmissionNumber { get; set; }
        public string StudentName { get; set; }
        public string Nationality { get; set; }
        public string MotherTongue { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string subCaste { get; set; }
        public string BirthPlace { get; set; }
        public string DateOfBirth { get; set; }
        public string DateOfBirthInWords { get; set; }
        public string PrevSchoolName { get; set; }
        public string AdmittedInClass { get; set; }
        public string AdmissionDate { get; set; }
        public string Progress { get; set; }
        public string Behaviour { get; set; }
        public string DateOfSchoolLeaving { get; set; }
        public string ClassFromLeft { get; set; }
        public string CertRecDate { get; set; }
        public string ReceivedBy { get; set; }
    }
}
